---
# Load Debian Import tasks
- name: (Debian) Load tasks
  import_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"

# Load Redhat Import tasks
- name: (Redhat) Load tasks
  import_tasks: redhat.yml
  when: ansible_facts['os_family'] in ['RedHat', 'Rocky']

# Common tasks
- name: Add "main_user" to docker group
  ansible.builtin.user:
    name: "{{ main_user }}"
    groups: docker
    append: yes
    state: present
  when: main_user is defined
